/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { AaveLendingPoolProviderV2 } from "../AaveLendingPoolProviderV2";

export class AaveLendingPoolProviderV2__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AaveLendingPoolProviderV2 {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as AaveLendingPoolProviderV2;
  }
}

const _abi = [
  {
    inputs: [],
    name: "getLendingPool",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
